### ISSUE TITLE
TRANSIT fade time faulty on Windows until precision set

### ISSUE THREAD

**Issue by DaveBenham** [stoermelder/vcvrack-packone#323] opened 2022-06-09 01:11 UTC
I'm using the latest development build from 2022-05-24 on both Windows and M1 Mac running rack 2.06 pro standalone.

On Windows only the TRANSIT fade time is very fast upon loading a patch. The fade time is restored to normal if I set the precision in the context menu, even if I select the currently checked precision. I have to go through the same process every time I open the patch.

I am not experiencing the problem on Mac.

**Comment by stoermelder** [comment] 2022-09-11 07:26
I'm affraid I can't reproduce the problem. Can you provide a patch file?

**Comment by DaveBenham** [comment] 2022-09-12 12:21
No worries, the problem has been fixed.

I built a simple test patch with the older version of packone on Windows from May, and verified the problem.

Then I downloaded the most recent version from 9/11, and the problem has disappeared.

I have a video of the old bug in action if you are interested. But I think the issue is moot at this point.

**Comment by stoermelder** [comment] 2022-09-12 19:08
Thanks for reporting back. I thought so as this was fixed in 37d7231cea2de8a45c3ecf81564eb507c282a495

**Closed as completed** 2022-09-12 19:09 UTC
