### ISSUE TITLE
TRANSIT +T Doesn't work

### ISSUE THREAD

**Issue by Outboarder** [stoermelder/vcvrack-packone#177] opened 2020-09-07 19:46 UTC
Hi

When I add +T (on the TRNASITs right side) buttons are grayed out and it's unable to recall preset.  

Thank you for this amazing collection.

**Comment by stoermelder** [comment] 2020-09-07 19:48
Duplicate of #174:
https://github.com/stoermelder/vcvrack-packone/issues/174#issuecomment-683399264

**Closed as completed by stoermelder** 2020-09-07 19:48 UTC
