### ISSUE TITLE
Remove .Rack 2.0.4 vst Phase extremely hi CPU Usage

### ISSUE THREAD

**Issue by GenCode00** [stoermelder/vcvrack-packone#315] opened 2021-12-31 04:51 UTC
if i use phase input it maxes out cpu to freeze completely with nothing else but 1 osc  and mixer in a project . nothing else in a DAW
running ,. no effect or other vsts . its working fine in Rack v1  1% usage . stand alone Rack 2.0.4 its not working at all . can't even engage record button .

**Comment by GenCode00** [comment] 2021-12-31 04:53
its on Mac . forgot to mention

**Comment by stoermelder** [comment] 2022-01-26 18:36
Duplicate of #306.

**Closed as completed by stoermelder** 2022-01-26 18:36 UTC
Labels: duplicate
