### ISSUE TITLE
STRIP - Something strange with locating saved strips

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#4] opened 2019-06-29 14:16 UTC
Hi Ben! Sometimes Strips doesn't even see vcsss files in the folder, but sometimes it do. But I've got such a strange Windows 10 error when load it, you can look at the screenshot.
![2019-06-29_17-16-28](https://user-images.githubusercontent.com/42435368/60385429-a8890c00-9a91-11e9-8ca0-574d88ebc48c.png)

**Comment by stoermelder** [comment] 2019-06-29 17:28
Should already been fixed in the latest build from commit 9cb5dc7.
The file-browser issue is caused by Rack and will be fixed in its next release.
https://github.com/VCVRack/Rack/issues/1407

**Comment by stoermelder** [comment] 2019-07-01 09:42
Rack v1.1.1 has been released. Can you check if these problems are gone?

**Comment by vcvrackideas** [comment] 2019-07-01 15:56
Now it see the files but when I'm trying to load vcsss it shows me again this, but it works when I'm pressing 3-4 times "ignore" button 
![2019-07-01_18-53-22](https://user-images.githubusercontent.com/42435368/60450161-e91f8b80-9c31-11e9-8dba-a151e1496c7a.png)

**Comment by stoermelder** [comment] 2019-07-01 16:08
Are you using the latest build? I've fixed this issue some time ago and never experienced it again.
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by vcvrackideas** [comment] 2019-07-01 16:21
oooh, my fault!  just download win build and everything works awesome! thank you

**Comment by stoermelder** [comment] 2019-07-01 16:23
No problem, thanks for reporting anyway!

**Closed as completed by stoermelder** 2019-07-01 16:23 UTC
Labels: bug
