### ISSUE TITLE
8Face Mk2 Bound Modules doesn't survive "Save Selection As..." followed by "Import Selection..."

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#317] opened 2022-02-23 16:29 UTC
If I save a collection of modules containing an 8Face Mk2 with Stoermelder Strip, it remembers all the bindings for the 8Face.

If I do "Save Selection As" followed by "Import Selection" the 8Face bindings are gone.

I haven't dug into the code, but somehow what happens when you paste a strip (or load & save) restores the 8Face Mk2 with bindings intact, but Rack2 "Import Selection" does not.

**Comment by stoermelder** [comment] 2022-09-11 07:51
Please let me know if this problem persists with the current version of Rack 2.1.2:

2.1.2 (2022-07-04)
- Fix expanders not updating (connecting or disconnecting to adjacent modules) when cloning or removing modules.

https://github.com/VCVRack/Rack/blob/v2/CHANGELOG.md

**Comment by stoermelder** [comment] 2022-09-15 21:59
Duplicate of #326

**Closed as completed by stoermelder** 2022-09-15 21:59 UTC
Labels: duplicate
