### ISSUE TITLE
MIDI-STEP - Changing theme to dark default can freeze upon close

### ISSUE THREAD

**Issue by Coirt** [stoermelder/vcvrack-packone#88] opened 2020-01-10 21:02 UTC
OS: Windows 10
rack version: dev.7a789af / release

When setting theme to dark by default a couple things go wrong. 

1. The module you set the theme from does not change its theme to dark when in the Rack but it will change all in the browser upon reopening. Upon opening Rack the module you change to dark from will still be blue in the Rack.

2. Upon close after changing the theme Rack can sometimes freeze no stack trace available in `debug` have to close with task manager or repeatedly press close. This also happens in release when you add a module that is not able to set the theme to dark when added to the rack.

Think the issue here is when there is modules in the rack it can't change their theme when setting `by default` but it does change the theme when set to dark individually, It will change their theme in the browser just fine with `by default`. When you add the changed dark theme from the browser it will be dark, but some modules will not be dark by default even though they are in the browser.

not much use but [here's the log](https://pastebin.com/r9ABxjkq)

steps likely to reproduce:

- add 1 module change to dark by default, close / re-open Rack 
- add another module disable dark by default 
- close / reopen, repeat.

You will be left with the original panel added (blue theme) 2nd added (dark theme) 3rd (blue theme) etc. non will be the defaulted colour in the Rack but will be in the Browser.

**Comment by stoermelder** [comment] 2020-01-10 21:14
I'm not sure if I understand correctly. The "default" setting won't change any of the modules already added to the patch. Only new modules will apply the default setting on add. Each module stores its theme within the patch and will only change by the the individual setting.

**Comment by Coirt** [comment] 2020-01-10 21:34
Dark as default is not a global thing?

Added all and the freeze bug seems to occur with midi step

![themeBug3](https://user-images.githubusercontent.com/12150421/72187889-cf38df80-33f0-11ea-904f-f969bdc6d29f.PNG)

**Comment by stoermelder** [comment] 2020-01-10 21:54
"Dark as default" is a global thing but only for new modules. It does nothing for modules already added to the patch.

Can't reproduce any freezing. Will look further.

**Comment by Coirt** [comment] 2020-01-10 22:04
Ah okay it is the same with other modules with dark themes, I see. If you can change individually to dark could you use `extrn` to change all to dark as default when clicked from 1 module even if in the rack.

**Comment by Coirt** [comment] 2020-01-11 06:52
It is difficult to reproduce the freezing now for me also. Will keep trying but here is what midi step does when set to dark first and then dark as default:

![ThemeBug_1](https://user-images.githubusercontent.com/12150421/72200369-814bc800-3440-11ea-900c-d7f18cdd6181.gif)

_Also happens without setting dark first_

**Comment by stoermelder** [comment] 2020-01-11 09:12
Ah ok, thanks, fixed in 68c847bc1a04f1121b9a442ba92227b04be15102.
Still trying to reproduce the freezing. It might be caused by Rack's MIDI API which caused some crashes for me in the past.

**Comment by stoermelder** [comment] 2020-04-11 17:41
I think this issue had been resolved.

**Closed as completed by stoermelder** 2020-04-11 17:41 UTC
Labels: bug
