### ISSUE TITLE
Arena only mix 1 works correctly mix 2-4 do NOT.

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#147] opened 2020-07-13 14:48 UTC
Hi Ben,
I attached a vcv file to show that after loading it only the mix 1 channel works as it should , the other 3 do not output anything, or just a constant volume, they do not react on distance.
I hope you understand what I mean.

Greetings Peter.

[Arena Bug - 13072020.zip](https://github.com/stoermelder/vcvrack-packone/files/4913205/Arena.Bug.-.13072020.zip)

**Comment by stoermelder** [comment] 2020-07-18 09:21
Thanks for reporting. Duplicate of #113.

**Closed as completed by stoermelder** 2020-07-18 09:21 UTC
Labels: duplicate

**Comment by Petervos2018** [comment] 2020-07-18 11:37
Sorry had not seen #113 , would have posted there.

Thanks for fixing 👍
