### ISSUE TITLE
Rotor consistently crashes on ≈10V mod input

### ISSUE THREAD

**Issue by Andreya-Autumn** [stoermelder/vcvrack-packone#365] opened 2023-03-07 17:14 UTC
Hello! And big thanks for the useful modules. <3 

I'm encountering the problem described in the title. 
I'm on Rack Free 2.1.3, M1 Mac, OS11.6.5. 
Attaching the crash log, and the patch that triggers it. (The patch needs some plugins, lemme know if you want me to set up a barebones repro patch).
Bringing the Bogaudio constant voltage to 10 crashes every time for me. 
[Rotor Crash.txt](https://github.com/stoermelder/vcvrack-packone/files/10912063/Rotor.Crash.txt)
[SaunaDrone.vcv.zip](https://github.com/stoermelder/vcvrack-packone/files/10912064/SaunaDrone.vcv.zip)

**Comment by stoermelder** [comment] 2023-10-03 13:27
Thanks for reporting, unfortunately I can't reproduce any crash with you patch. I tried it on Windows and I don't have an easy way to test it on a M1 Mac right now.
I reviewed the code and can only think of one issue which could occor by numeric precision while rounding numbers. I added some failsafe for this, but it needs confirmation. Please let me know if it still crashes using the latest build (I only provide x64 preview builds for Mac at the moment).
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by Andreya-Autumn** [comment] 2023-10-04 17:24
Thanks! I managed to inadvertently install arm rack over intel rack recently so I gotta get a dual install going to test this. Maybe I'll find the time soon. The good news are I'm also not getting the crash anymore on Arm!

**Comment by stoermelder** [comment] 2023-10-04 18:42
I close this issue for now. Feel free to respond if you experience more crashes.

**Closed as completed by stoermelder** 2023-10-04 18:42 UTC
Labels: bug
