### ISSUE TITLE
uMap in VCV VST high CPU Usage

### ISSUE THREAD

**Issue by thorinside** [stoermelder/vcvrack-packone#311] opened 2021-12-13 03:34 UTC
Running VCV Pro 2.0.3b, and have compiled your packone from the latest v2-dev branch, on a Mac.

![Screen Shot 2021-12-12 at 8 27 06 PM](https://user-images.githubusercontent.com/291679/145747919-4e0829d4-9dfb-4451-b228-4c8b2a30d5fc.png)

I have found that in the VST, uMap consumes pretty much all available CPU. I tried in Bitwig 4.1.1, screenshot above.

The following screenshot is from Reason 12, which seems to have even worse performance.
![Screen Shot 2021-12-12 at 8 31 20 PM](https://user-images.githubusercontent.com/291679/145748172-b507d964-f6c3-4a4e-9524-62b6c2520f58.png)

In VCV Standalone, as long as no VST instances are running, the CPU usage seems completely fine.

**Comment by stoermelder** [comment] 2021-12-13 19:33
Duplicate of #306.

**Closed as completed by stoermelder** 2021-12-13 19:33 UTC
Labels: duplicate
