### ISSUE TITLE
8FACE - slot start incorrect

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#27] opened 2019-07-20 15:22 UTC
Hi there Ben,

when i give 8Face a clock (Clocked Impromptu), and set 8Face to "seq trigger"
on pressing run from Clocked, 8Face will always jump to 2nd position and start from there. 
This is not desired. 

And when i set 8Face to "Clock" and give it clock from Clocked Impromptu, 8Face does not respond. Is that normal?

**Comment by Coirt** [comment] 2019-07-20 15:31
Well it is on the first pattern already so I'd say this is normal behaviour. One way to work around it might be to set 8Face to the last preset when you feed it a clock.

Clocks / triggers usually or should respond to between 1-2v [(manual)](https://vcvrack.com/manual/VoltageStandards.html#triggers-and-gates) clocked spits out 10 volts.

**Comment by stoermelder** [comment] 2019-07-20 15:34
Hi Latif!
First issue: there was a problem with early versions of 8FACE, but I can't reproduce this behaviour with the released version. Are you sure you are using the version from the library? If yes, can you provide a patch and I'll check whats going on.

Second issue: yes, this is how it is supposed to work. In clock-mode a manual button press is delayed until the next clock trigger, so preset changes happen on the clock. If no button is touched nothing is going to happen ;-)

**Comment by Eurikon** [comment] 2019-07-20 15:46
> 
> Second issue: yes, this is how it is supposed to work. In clock-mode a manual button press is delayed until the next clock trigger, so preset changes happen on the clock. If no button is touched nothing is going to happen ;-)

Thanks Ben, i just realized this about 30 seconds ago, while fiddling with it.
This is like an "arm/quantized" function, ok got it! :) 

I will send you a patch about the first issue, but first i will make sure that it is what i am experiencing.

**Comment by Eurikon** [comment] 2019-07-20 15:54
Ok i made sure that it is what i am experiencing. 
I will send you the patch in community forum inbox.
Simply press start on Clocked, and 8Face will instantly jump to 2nd slot and start from there :)

**Comment by stoermelder** [comment] 2019-07-20 16:09
Hm, I see what you mean. I checked SEQ-3 and it behaves the same... I'm not sure...

**Comment by Eurikon** [comment] 2019-07-20 16:16
ok, take your time.
For now i found that if i keep the "output reset high when not running" ,
8Face operates how i want it. 
But that option in the Clock is not always preferred, as it will also send the same state to other parts in the patch where i don't want it.
Anyway maybe it can hint you in the right direction. :)

**Comment by stoermelder** [comment] 2019-07-21 08:19
What I meant was that I'm not sure if there is a problem. The option "output reset high when not running" is enabled by default on Clocked and I checked several sequencers and all behave this way when disabling this option. What is the reason you want to disable it?

**Comment by Eurikon** [comment] 2019-07-21 10:29
I can't remember exactly what problem it was causing for me, cause it has been changed for a while now by Marc. 
But i do remember that when it got introduced i had some patches with fx in it go crazy, so i defaulted to disabling it since i didn't need that state anyway.

That state was introduced for a request from users, for sequencers to stop and retain at the position where they stopped.
And for me that was not necessary, cause i nearly always want the sequencer to stop and start from beginning, which Marc's sequencers did by default.

Anyway i will start using this "output reset high when not running", until i run into that problem again (if any) :)

**Comment by stoermelder** [comment] 2019-07-21 17:24
Ok, I close this issue for now. Please feel free to add a comment and I reopen if necsessary!

**Closed as completed by stoermelder** 2019-07-21 17:24 UTC
Labels: help wanted
